import type { AppProps } from 'next/app'
import type { Metadata } from "next";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Sign Up",
  description: "Generated by create next app",
};

export default function App({ Component, pageProps }: AppProps) {
  return (
    <Component {...pageProps} />
  )
}